### ISSUE TITLE
LoadError: windows/error

### ISSUE THREAD

**Issue by mcquin** [chef-cookbooks/windows#276]
Unable to compile the windows cookbook in a recipe which depends on it.

System: win2012r2-x86_64
Chef client version: 12.5.0.current.0 (64-bit)

Error:
```
LoadError
-------------
cannot load such file -- windows/error
```
Cause: https://github.com/chef-cookbooks/windows/blob/master/libraries/windows_privileged.rb#L24

Repro: 
```
# Clone this repository and cd to it
git clone https://github.com/adamedx/winbox
cd winbox

# Use Berkshelf to download all cookbook dependencies:
berks vendor cookbooks

# Run `chef-client` in local mode to configure the workstation!
chef-client -z --color -o 'winbox'
```

**Comment by mcquin** [comment]
It looks like `windows/*` comes from the `windows-pr` gem, which is being removed from Chef.

**Comment by rcsavage** [comment]
Confirmed, I ran into this problem as well.   I simply went into C:\opscode\Chef\embedded\bin, and then a gem install windows-pr and that fixed the problem.   Thank you mcquin for finding this.

**Comment by jfbibeau** [comment]
Sorry to comment on a closed issue, but does this mean this cookbook isn't compatible with Chef 12.5.1 until the commit referenced above goes in a cookbook release?

**Comment by mcquin** [comment]
@jfbibeau It looks like version 1.38.2 of this cookbook is released on Supermarket. The fix is included in 1.38.2, so if you update your windows cookbook dependency it should work with Chef 12.5+.

**Comment by jfbibeau** [comment]
@mcquin Of course, sorry I missed that. 1.38.2 fixed the issue. Cheers.

**Comment by JackChance** [comment]
still an issue with windows 1.44.3

**Comment by mwrock** [comment]
what version of the chef client @JackChance ?

**Comment by JackChance** [comment]
12.6.0



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by JackChance** [comment]
Sorry, let me add more details. I'm bootstrapping from OEL 6.5 to win2012r2.

OEL 6.5 bootstrapper has ChefDK 0.13.21 which includes chef-client 12.9.41
win2012r2 bootstrappee has chef-client 12.6.0.

Bootstrap succeeds in registering to chef server and installing client, fails when it attempts to include windows/errors. Attempted to `chef gem install windows-pr` also errors out, with well over a hundred errors..

```
make "DESTDIR="
compiling win32/api.c
win32/api.c:2:21: error: windows.h: No such file or directory
win32/api.c:33: error: expected specifier-qualifier-list before ‘HANDLE’
win32/api.c: In function ‘api_free’:
win32/api.c:40: error: ‘Win32API’ has no member named ‘library’
win32/api.c:41: error: ‘Win32API’ has no member named ‘library’
win32/api.c: At top level:
win32/api.c:58: error: expected ‘)’ before ‘dwError’
win32/api.c: In function ‘callback_init’:
win32/api.c:189: error: ‘LPARAM’ undeclared (first use in this function)
win32/api.c:189: error: (Each undeclared identifier is reported only once
win32/api.c:189: error: for each function it appears in.)
win32/api.c:189: error: expected ‘)’ before ‘find_callback’
win32/api.c: In function ‘api_init’:
win32/api.c:236: error: ‘HMODULE’ undeclared (first use in this function)
win32/api.c:236: error: expected ‘;’ before ‘hLibrary’
win32/api.c:237: error: ‘FARPROC’ undeclared (first use in this function)
win32/api.c:237: error: expected ‘;’ before ‘fProc’
win32/api.c:273: error: ‘hLibrary’ undeclared (first use in this function)
win32/api.c:283: error: ‘Win32API’ has no member named ‘library’
win32/api.c:290: error: ‘fProc’ undeclared (first use in this function)
win32/api.c:333: error: ‘Win32API’ has no member named ‘function’
win32/api.c:341: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:344: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:347: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:350: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:353: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:356: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:370: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:376: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:379: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:382: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:385: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:388: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c: In function ‘func_init’:
win32/api.c:459: error: ‘Win32API’ has no member named ‘function’
win32/api.c:459: error: ‘FARPROC’ undeclared (first use in this function)
win32/api.c:459: error: expected ‘;’ before ‘rb_num2long_inline’
win32/api.c:467: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:470: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:473: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:476: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:479: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:482: error: ‘Win32API’ has no member named ‘prototype’
win32/api.c:496: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:502: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:505: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:508: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:511: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c:514: error: ‘Win32API’ has no member named ‘return_type’
win32/api.c: At top level:
win32/api.c:531: error: expected specifier-qualifier-list before ‘DWORD’
win32/api.c:535: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘CallbackFunction’
...
win32/api.c:712: error: ‘CallbackFunction9_8’ undeclared here (not in a function)
win32/api.c:712: error: ‘CallbackFunction9_9’ undeclared here (not in a function)
...
```
`chef gem install win32-api` gives the same errors

**Comment by mwrock** [comment]
Can you try with a later chef-client on the node?

**Comment by JackChance** [comment]
Same error on the following clients
12.9.41
12.13.30
12.13.37
