### ISSUE TITLE
undefined method `interactive_enabled' for Chef::Resource::WindowsTask

### ISSUE THREAD

**Issue by puneetloya** [chef-cookbooks/windows#262]
Worked in 1.37.0 but not working in 1.38.1

**Comment by gyoza** [comment]
Same issue here.

**Comment by gyoza** [comment]
I am also seeing this in 1.37.1 on windows 2008 R2 with chef 12.4.1.

**Comment by tas50** [comment]
As of Chef 13 we've moved the windows_task resource into the chef-client itself. There's been a significant amount of work there to resolve many of the outstanding issues with windows_task in this cookbook. Since we have a much improved codebase included in chef-client now we won't be continuing to work on the resource in this cookbook, and will eventually remove it altogether. At this time I'm going to close out this issue, and I'd encourage you to try the latest Chef 13 release. If you still have issues please file them against chef itself.
